# -*- coding: utf-8 -*-
"""FuncionCoseno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJ_A8plsrGThrnYbbuWBwKVDQRUzIFU3
"""

import math

def distancia_coseno(x, y):
    if len(x) != len(y):
        raise ValueError("Los vectores deben tener la misma longitud")

    suma = 0
    cx=0
    cy=0
    for i in range(len(x)):
        suma += abs(x[i] * y[i])
    for i in range(len(x)):
      cx += abs(x[i]**2)
      cy += abs(y[i]**2)

    raizx=cx**(1/2)
    raizy=cy**(1/2)
    distancia=suma/(raizx*raizy)
    return distancia

vector1 = [1, 1, 2, 1, 1, 0, 1, 1, 0]
vector2 = [1, 1, 0, 1, 0, 1, 0, 0, 1]
dist =1- (distancia_coseno(vector1, vector2))
print(f"Distancia de Coseno: {dist}")