# -*- coding: utf-8 -*-
"""practica 1.3 AHORA SI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNA2bc6khqRaj0ybUCRi7W49LMGpMhKN
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import xlrd

#importar datos

data = pd.read_excel('/content/drive/MyDrive/movie-DB-2000s.xlsx')
#data.describe()
data.head(10)

#nuevo df para guardar solo los datos númericos de la base de datos iris
w = data
new_data = w[['Title','Genres','Actor1','Actor2','Actor3']].copy()
new_data.head(10)

from jaccard1 import jaccard_distancia

"""Opción 1"""

import pandas as pd

df = new_data

busqueda = input("Busqueda: ")

print(f"Estos son los resultados para '{busqueda}' \n")

info = []

for index, row in df.iterrows():
    title = row['Title']
    genres = row['Genres']
    actor1 = str(row['Actor1'])
    actor2 = str(row['Actor2'])
    actor3 = str(row['Actor3'])

    distancia_titulo = jaccard_distancia(busqueda, title)
    distancia_genero = jaccard_distancia(busqueda, genres)
    distancia_actor1 = jaccard_distancia(busqueda, actor1)
    distancia_actor2 = jaccard_distancia(busqueda, actor2)
    distancia_actor3 = jaccard_distancia(busqueda, actor3)


    info.append((distancia_titulo, title, genres, actor1, actor2, actor3))
    info.append((distancia_genero, title, genres, actor1, actor2, actor3))
    info.append((distancia_actor1, title, genres, actor1, actor2, actor3))
    info.append((distancia_actor2, title, genres, actor1, actor2, actor3))
    info.append((distancia_actor3, title, genres, actor1, actor2, actor3))



info.sort(reverse=True)


peliculas = set()


contador = 0
for distancia, titulo, genero, actor1, actor2, actor3 in info:
    if titulo not in peliculas:
        distancia = round(distancia, 4)
        print(f"Título: {titulo}")
        print(f"Género: {genero}")
        print(f"Actores: {actor1}, {actor2}, {actor3}")
        print(f"Distancia: {distancia}")
        print()
        peliculas.add(titulo)
        contador += 1

    if contador >= 5:
        break

"""Opción 2 (lo mismo pero sin el input)"""

import pandas as pd

df = new_data

busqueda = "Emma Stone"

print(f"Estos son los resultados para '{busqueda}' \n")

info = []

for index, row in df.iterrows():
    title = row['Title']
    genres = row['Genres']
    actor1 = str(row['Actor1'])
    actor2 = str(row['Actor2'])
    actor3 = str(row['Actor3'])

    distancia_titulo = jaccard_distancia(busqueda, title)
    distancia_genero = jaccard_distancia(busqueda, genres)
    distancia_actor1 = jaccard_distancia(busqueda, actor1)
    distancia_actor2 = jaccard_distancia(busqueda, actor2)
    distancia_actor3 = jaccard_distancia(busqueda, actor3)


    info.append((distancia_titulo, title, genres, actor1, actor2, actor3))
    info.append((distancia_genero, title, genres, actor1, actor2, actor3))
    info.append((distancia_actor1, title, genres, actor1, actor2, actor3))
    info.append((distancia_actor2, title, genres, actor1, actor2, actor3))
    info.append((distancia_actor3, title, genres, actor1, actor2, actor3))



info.sort(reverse=True)


peliculas = set()


contador = 0
for distancia, titulo, genero, actor1, actor2, actor3 in info:
    if titulo not in peliculas:
        distancia = round(distancia, 4)
        print(f"Título: {titulo}")
        print(f"Género: {genero}")
        print(f"Actores: {actor1}, {actor2}, {actor3}")
        print(f"Distancia: {distancia}")
        print()
        peliculas.add(titulo)
        contador += 1

    if contador >= 5:
        break